{
    "data": [
        {
            "dateTime": "2024-07-24T11:29:26.380000",
            "history": {
                "balancedMeals": "",
                "doerLevel": "6",
                "emotionalLevel": "",
                "exerciseDetails": "",
                "exerciseRegularly": "",
                "explainRejections": "None",
                "friendshipsImportance": "",
                "generalHealthLevel": "",
                "healthConcernDetails": "Test",
                "healthConcerns": "Yes",
                "imageryLevel": "",
                "medications": "",
                "sensationsLevel": "",
                "thinkerPlannerLevel": ""
            },
            "id": 35,
            "pageNo": 11,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T14:59:03.061000",
            "id": 37,
            "pageNo": 12,
            "questions": {
                "Alcohol": "Rarely",
                "Allergies": "Rarely",
                "Aspirin": "Rarely",
                "Backaches": "Frequently",
                "Birth control pills": "Occasionally",
                "Bruise or bleed easily": "Daily",
                "Chest pain": "Frequently",
                "Cigarettes": "Occasionally",
                "Cocaine": "Never",
                "Coffee": "Never",
                "Constipation": "Never",
                "Diarrhea": "Rarely",
                "Diet pills": "Frequently",
                "Diuretics": "Occasionally",
                "Dizziness": "Occasionally",
                "Earaches": "Rarely",
                "Early morning awakening": "Never",
                "Eat junk foods": "Occasionally",
                "Fatigue": "Never",
                "Fitful sleep": "Rarely",
                "Gas": "Rarely",
                "Hallucinogens (e.g. LSD)": "Daily",
                "Headaches": "Occasionally",
                "Heartburn": "Frequently",
                "High blood pressure": "Occasionally",
                "Hormones": "Frequently",
                "Indigestion": "Occasionally",
                "Insomnia": "Frequently",
                "Laxatives": "Frequently",
                "Marijuana": "Daily",
                "Muscle weakness": "Never",
                "Narcotics": "Occasionally",
                "Nausea": "Frequently",
                "Overeat": "Frequently",
                "Pain Killers": "Rarely",
                "Palpitations": "Rarely",
                "Shortness of breath": "Daily",
                "Sleep too much": "Occasionally",
                "Sleeping pills": "Occasionally",
                "Stimulants": "Frequently",
                "Tobacco (specify)": "Rarely",
                "Tranquilizers": "Rarely",
                "Undereat": "Daily",
                "Vitamins": "Frequently",
                "Vomiting": "Daily",
                "Weight problems": "Frequently",
                "significantMemories": "Final test"
            },
            "userId": 8
        },
        {
            "dateTime": "2024-07-24T10:20:53.861000",
            "history": {
                "address": "Nairobi",
                "age": "27",
                "attemptedSuicide": "",
                "date": "2024-07-24",
                "dateOfBirth": "2024-07-01",
                "emergencyContact": "Isaiah",
                "emergencyContactTelephone": "+254748800714",
                "familyEmotionalDisorder": "No",
                "familyPhysician": "Yes",
                "familySuicide": "No",
                "height": "23",
                "hospitalizationDetails": "",
                "hospitalizedBefore": "Yes",
                "hospitalizedDetails": "ESS",
                "livingIn": "",
                "livingWith": [],
                "maritalStatus": "Married",
                "maritalTimes": "",
                "name": "Ouma John",
                "numberOfChildren": "4",
                "occupation": "Developer",
                "otherLiving": "",
                "pastJobs": "",
                "physicianName": "Ouma John",
                "physicianTelephone": "+254748800714",
                "placeOfBirth": "Nairobi",
                "presentWork": "",
                "referredBy": "Ous",
                "religion": "None",
                "sex": "Male",
                "spouseAge": "24",
                "spouseName": "Grace",
                "spouseOccupation": "Business",
                "telephone": {
                    "day": "254748800714",
                    "evening": ""
                },
                "therapyBefore": "",
                "weight": "22",
                "weightFluctuate": "No",
                "workSatisfaction": "",
                "workSatisfactionExplanation": ""
            },
            "id": 25,
            "pageNo": 1,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T10:23:46.326000",
            "history": {
                "brothersAges": "16-40",
                "confideParents": "Yes",
                "discipline": "Viboko",
                "fatherAge": "84",
                "fatherDeathAge": "",
                "fatherDeathCause": "N/A",
                "fatherDeathTime": "",
                "fatherHealth": "Healthy",
                "fatherName": "Ambuka",
                "fatherOccupation": "Farmer",
                "fatherPersonality": "Firm",
                "feelLoved": "Yes",
                "homeAtmosphere": "Loving",
                "interference": "No",
                "interferenceDetails": "",
                "lastGrade": "F4",
                "motherAge": "60",
                "motherDeathAge": "",
                "motherDeathCause": "N/A",
                "motherDeathTime": "",
                "motherHealth": "Healthy",
                "motherName": "Atieno",
                "motherOccupation": "Farmer",
                "motherPersonality": "Calm",
                "raisedBy": "N/A",
                "scholasticStrengths": "Average",
                "scholasticWeaknesses": "Average",
                "siblingsDetails": "Nothing",
                "sistersAges": "0",
                "stepParentAge": "0"
            },
            "id": 26,
            "pageNo": 2,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T10:25:16.680000",
            "history": {
                "childhoodIssues": {
                    "deathInFamily": true,
                    "drugUse": true,
                    "eatingDisorder": true,
                    "emotionalProblems": true,
                    "financialProblems": true,
                    "happyChildhood": true,
                    "ignored": true,
                    "legalTrouble": true,
                    "medicalProblems": true,
                    "notEnoughFriends": true,
                    "others": "",
                    "schoolProblems": true,
                    "severelyBullied": true,
                    "severelyPunished": true,
                    "sexuallyAbused": true,
                    "strongReligiousConvictions": true,
                    "unhappyChildhood": true,
                    "usedAlcohol": true
                },
                "presentingProblems": {
                    "helpfulAttempts": "Coding",
                    "mainProblems": "Test",
                    "problemStart": "Yesterday",
                    "problemWorsen": "Unemployment",
                    "severity": "Very severe"
                },
                "satisfactionAndTension": {
                    "lifeSatisfaction": "3",
                    "overallTension": "3"
                },
                "therapyExpectations": {
                    "aboutTherapy": "Test",
                    "therapistQualities": "Understanding",
                    "therapyDuration": "2 weeks"
                }
            },
            "id": 27,
            "pageNo": 3,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T10:25:58.851000",
            "history": {
                "modalityAnalysis": {
                    "behaviors": {
                        "aggressiveBehavior": true,
                        "cantKeepAJob": true,
                        "compulsions": true,
                        "concentrationDifficulties": true,
                        "crying": true,
                        "drinkTooMuch": true,
                        "eatingProblems": true,
                        "impulsiveReactions": true,
                        "insomnia": true,
                        "lazy": true,
                        "lossOfControl": true,
                        "nervousTics": true,
                        "oddBehavior": true,
                        "others": "N/A",
                        "outburstsOfTemper": true,
                        "overEat": true,
                        "phobicAvoidance": true,
                        "procrastination": true,
                        "sleepDisturbance": true,
                        "smoke": true,
                        "spendTooMuchMoney": true,
                        "suicidalAttempts": true,
                        "takeDrugs": true,
                        "takeTooManyRisks": true,
                        "unassertive": true,
                        "withdrawal": true,
                        "workTooHard": true
                    }
                }
            },
            "id": 28,
            "pageNo": 4,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T10:27:12.624000",
            "history": {
                "feelings": {
                    "angry": true,
                    "annoyed": true,
                    "anxious": true,
                    "bored": true,
                    "conflicted": true,
                    "contented": true,
                    "depressed": true,
                    "energetic": true,
                    "envious": true,
                    "excited": false,
                    "fearful": true,
                    "guilty": true,
                    "happy": true,
                    "helpless": true,
                    "hopeful": true,
                    "hopeless": true,
                    "jealous": true,
                    "lonely": true,
                    "optimistic": true,
                    "panicky": true,
                    "regretful": true,
                    "relaxed": true,
                    "restless": true,
                    "sad": true,
                    "shameful": true,
                    "tense": true,
                    "unhappy": true
                },
                "relaxationAndWishes": {
                    "troubleRelaxing": "No",
                    "troubleRelaxingExplanation": "",
                    "twoWishes": "Test1 and Test 2"
                },
                "talentsAndSkills": {
                    "freeTimeSpent": "Test",
                    "hobbies": "Test",
                    "specialTalents": "Volleyball",
                    "startDoing": "Coding",
                    "stopDoing": "Test"
                }
            },
            "id": 29,
            "pageNo": 5,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T10:28:34.167000",
            "history": {
                "calmSituations": "Many",
                "fears": [
                    "Test1",
                    "Test2",
                    "Test3",
                    "Test4",
                    "Test5"
                ],
                "loseControlSituations": "None",
                "physicalSensations": {
                    "abdominalPain": true,
                    "backPain": true,
                    "blackouts": true,
                    "bowelDisturbances": true,
                    "burningOrItchingSkin": true,
                    "chestPain": true,
                    "dizziness": true,
                    "dryMouth": true,
                    "excessiveSweating": true,
                    "faintingSpells": true,
                    "fatigue": true,
                    "flushes": true,
                    "headaches": true,
                    "hearThings": true,
                    "hearingProblems": true,
                    "menstrualDifficulties": true,
                    "muscleSpasms": true,
                    "nausea": true,
                    "numbness": true,
                    "other": "",
                    "painOrBurningWithUrination": true,
                    "palpitations": true,
                    "rapidHeartBeat": true,
                    "sexualDisturbances": true,
                    "skinProblems": true,
                    "stomachTrouble": true,
                    "tension": true,
                    "tics": true,
                    "tingling": true,
                    "tremors": true,
                    "twitches": true,
                    "unableToRelax": true,
                    "visualDisturbances": true,
                    "wateryEyes": true
                },
                "positiveFeelings": "Happy"
            },
            "id": 30,
            "pageNo": 6,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T10:31:20.658000",
            "history": {
                "botheredByThoughts": true,
                "botheredThoughtsDescription": "Test",
                "disturbingImages": "None",
                "negativeWorries": "None",
                "nightmaresFrequency": "None",
                "opinionStatements": {
                    "date_highschool": "",
                    "datingHighSchool": "",
                    "friendships": "",
                    "mistakes": ""
                },
                "pleasantImage": "Pleasant",
                "safePlace": "safe",
                "thoughts": {
                    "angry": true,
                    "anxious": true,
                    "ashamed": true,
                    "compulsions": true,
                    "confident": true,
                    "confused": true,
                    "delusions": true,
                    "depressed": true,
                    "dissociative": true,
                    "grandiose": true,
                    "guilty": true,
                    "hallucinations": true,
                    "hostile": true,
                    "hypochondriacal": false,
                    "impulsive": true,
                    "insecure": true,
                    "intelligent": true,
                    "lonely": true,
                    "magical": true,
                    "mystical": true,
                    "nihilistic": true,
                    "obsessions": true,
                    "otherThoughts": "None",
                    "paranoid": true,
                    "perfectionistic": true,
                    "phobic": false,
                    "psychotic": true,
                    "religious": true,
                    "somatic": false,
                    "suicidal": true
                },
                "unpleasantImage": "Unpleasant"
            },
            "id": 31,
            "pageNo": 7,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T11:00:22.263000",
            "history": {
                "anyProblemsInRelationshipWithOtherPeople": false,
                "bulliedOrTeased": true,
                "childrenWithproblems": true,
                "childrenWithproblemsExplanation": "",
                "currentlyDisturbedByAnyPastRejectionsOrLossofLove": true,
                "dateDuringCollege": true,
                "dateDuringHighSchool": true,
                "easeMakingFriends": true,
                "experiencedAnxietyOrGuiltOutOfSexOrMasturbation": true,
                "friendsToSharePrivateThoughts": true,
                "griefRelationship": "None",
                "howPleasedWithMarriage": false,
                "howYouGetAlongWithSpouseFriendsAndFamily": false,
                "joyRelationship": "All",
                "keepfriends": true,
                "marriageDetails": {
                    "anyChildrenPresentSpecialProblems": "",
                    "anyDedailsAboutPreviousMariages": "None",
                    "engagedDuration": "3",
                    "howPleasedWithMarriage": "",
                    "howYouGetAlongWithSpouseFriendsAndFamily": "",
                    "knownBeforeEngagement": "3",
                    "likeLeastAboutSpouse": "Unloving",
                    "likeMostAboutSpouse": "Loving",
                    "maritalSatisfactionFactors": "None",
                    "marriedDuration": "3",
                    "namesAndAgesOfChildren": "Test, Test2, Test3",
                    "numberOfChildren": "3",
                    "problemDescriprion": "None",
                    "spouseAge": "23",
                    "spouseOccupation": "Test",
                    "spousePersonality": "Loving"
                },
                "otherRelationships": {
                    "anyProblemsInRelationshipWithOtherPeople": "",
                    "currentlyDisturbedByAnyPastRejectionsOrLossofLove": "",
                    "iCouldShockYouBy": "3Test",
                    "myBestFriendThinksIAm": "5Test",
                    "mySpauseDescribesMeAs": "4Test",
                    "oneWayPeopleHurtMe": "Test",
                    "peopleWhoDislikeMe": "6Test",
                    "problemsWithRelationshipsExplanation": "",
                    "rejectionExplanation": "None"
                },
                "presentSexLifeSatisfactory": true,
                "privateThoughts": false,
                "sexualRelationships": {
                    "anxietyExplanation": "None",
                    "anyOtherDetailsAboutFirstOrSubsequentSexualExperiences": "None",
                    "anyOtherSexualConcern": "None",
                    "anySignificantHomosexualReactionsOrRelationships": "None",
                    "experiencedAnxietyOrGuiltOutOfSexOrMasturbation": "",
                    "parentsAttitudeTowardsSex": "Strict",
                    "presentSexLifeSatisfactory": "",
                    "presentSexLifeSatisfactoryExplanation": "None",
                    "whenAndHowKnewOfSex": "Free",
                    "whenBecameAwareofPersonalSexualImpulses": "2012"
                },
                "socialRelaxationDegree": false
            },
            "id": 32,
            "pageNo": 8,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T11:23:55.589000",
            "history": {
                "doer": "4",
                "emotional": "4",
                "imagery": "6",
                "interpersonal": "4",
                "sensations": "5",
                "thinker": "6"
            },
            "id": 33,
            "pageNo": 9,
            "patientId": 8,
            "patientName": "Ouma Arera"
        },
        {
            "dateTime": "2024-07-24T11:26:45.820000",
            "history": {
                "ageForFirstMenstrual": "none",
                "anyPhysicalHandicaps": "",
                "anySurgeryDescription": "",
                "balancedDiet": "Yes",
                "biologicalFactors": "4",
                "concernsAboutPhysicalHealth": "Yes",
                "dateOfLastPeriod": "2024-07-24",
                "experienceMenstrualPain": "No",
                "frequencyOfPhysicalExercise": "Test",
                "medicalConditions": "Test",
                "medicationCurrentlyTaking": "Test",
                "menstrualduration": "Test",
                "menstrualsRegular": "No",
                "mentrualsAffectMoods": "No",
                "physicalExercise": "Yes",
                "physicalHealthConcernsExplanation": "Test",
                "wasItAShock": "No",
                "whetherInformed": "No"
            },
            "id": 34,
            "pageNo": 10,
            "patientId": 8,
            "patientName": "Ouma Arera"
        }
    ],
    "message": "Data retrieved successfully",
    "status_code": 200,
    "successful": true
}